### ISSUE TITLE
Non used state STOPPED

### ISSUE THREAD

**Issue by mseroczynski** [PaulWoitaschek/AndroidPlayer#1]
It seems like State.STOPPED is never used here:
https://github.com/PaulWoitaschek/AndroidPlayer/blob/master/app/src/main/java/de/paul_woitaschek/mediaplayer/SpeedPlayer.kt

If you would rather see proper PR let me know.

**Comment by PaulWoitaschek** [comment]
Indeed, I removed it. 

When you find more things or have suggestions, feel free to open another issue!
